### ISSUE TITLE
Blacked out face

### ISSUE THREAD

**Issue by FewerFlaws** [cobrasrock/Skin-Swapper#10]
Step 1: Open skin changer
Step 2: Download "Notch"
Step 3: Change your skin to Notch.
Step 4: Download "<your_own_name>"
Step 5: Observe that Notch's skin appears there with a blacked out face.

**Comment by cobrasrock** [comment]
Funny enough Notch's skin is a bit of an exception as it has a black background instead of a transparent one. His skin is the only one I know of with this issue.

**Comment by FewerFlaws** [comment]
I'm reasonably sure I observed this behaviour without Notch's skin being involved.  Did you test this and find it can't be reproduced with other skins?
