### ISSUE TITLE
Issues after migration

### ISSUE THREAD

**Issue by RangoMcRoony** [cobrasrock/Skin-Swapper#19]
It doesn't seem to work on 1.16.5 after migrating my account, was working till this point now it just keeps the same skin regardless of if I change it

**Comment by cobrasrock** [comment]
A fix has been applied to the 1.17 version for this issue. I am still yet to apply this fix to previous versions.

**Comment by RangoMcRoony** [comment]
Brilliant, I look forward to it.

Ur doing an amazing job on this mod, really great work :)

**Comment by cobrasrock** [comment]
This should be fixed on the latest fabric and forge 1.16.5 versions on curseforge. https://www.curseforge.com/minecraft/mc-mods/skin-swapper/files

**Comment by RangoMcRoony** [comment]
will this also be implemented for 1.16.5 fabric?
