### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [cobrasrock/Skin-Swapper#2]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by cobrasrock** [comment]
I appreciate your concern. Unfortunately fabric is better. I am currently working on a forge version at a casual pace. Thank you for your patience.
