### ISSUE TITLE
Login button for Rauth/Oauth/other auth mods overlaps

### ISSUE THREAD

**Issue by srnyx** [cobrasrock/Skin-Swapper#21]
![image](https://user-images.githubusercontent.com/25808801/132247770-7f445761-a590-481a-9b66-e61dac9926af.png)

Maybe a config option (top right, bottom right, bottom left, top left [would need all of these as I also have ReplayMod]) for button location could be a permanent fix for stuff like this.

**Comment by cobrasrock** [comment]
I have added a config in newer fabric versions of the mod. You can access it via mod menu.
