### ISSUE TITLE
Mark MC 1.17.1 for version Skin Swapper 3.0.1

### ISSUE THREAD

**Issue by Disguys** [cobrasrock/Skin-Swapper#25]
Hello, author. Could you add a marker of version 1.17.1 for the new version of the Skin Swapper 3.0.1 mod on CurseForge site, I need it for the modpack.

**Comment by Disguys** [comment]
![image](https://user-images.githubusercontent.com/60795989/147881886-ddf41914-58e0-43ca-a65b-4d25ee8d518e.png)

**Comment by cobrasrock** [comment]
Although v3.0.1 for 1.18 works in 1.17, it was compiled with java 17 while many 1.17 users are using java 16. For now I will flag the mod for working in 1.17 but eventually I will upload a version compiled with java 16.

**Comment by Disguys** [comment]
thanks

**Comment by cobrasrock** [comment]
I have just changed the file to be back the way it was and uploaded a 1.17 fabric version.
