### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Lawerencium** [cobrasrock/Skin-Swapper#26]
I saw that both the fabric and forge version have been updated 4 days ago. the forge version was updated to 1.18, the fabric version is still 1.17. Could this one also be updated to 1.18 so that i can use it on my client.

Greetings,

**Comment by cobrasrock** [comment]
The latest 1.18 fabric version was updated a few days prior and can be found here https://www.curseforge.com/minecraft/mc-mods/skin-swapper/files/3586470
