### ISSUE TITLE
(1.19.2 Quilt) (Mod Conflict) Skin Swapper conflicts with 3D Skin Layers

### ISSUE THREAD

**Issue by TheRealDanini** [cobrasrock/Skin-Swapper#65]
Bug: When using the 3D Skin Layers mod with the Skin Swapper mod, selecting a skin causes the game to crash.

Steps to Reproduce

- Create a new instance with both the Skin Swapper mod installed and the 3D Skin Layers mod
- Launch the instance and go to multiplayer, then skins, and select any skin from the menu
- the game should crash
- disable or remove the 3D Skin Layers mod
- relaunch the game and select a skin, the game should not crash this time

Expected Result: The game should not crash
Actual Result: The game crashes and from what I can infer it is related to how the skin gets rendered on the side when clicked on, and something with the 3D Skin Layers mod causes the game to crash when it tries to render the preview of the skin

Mod Versions
skin swapper 3.1.2-1.19.2
3d skin layers 1.6.2-1.19.2 [Modrinth Page](https://modrinth.com/mod/3dskinlayers)

Crash Log
[crash-2024-02-26_12.51.38-client.txt](https://github.com/cobrasrock/Skin-Swapper/files/14408710/crash-2024-02-26_12.51.38-client.txt)

**Comment by Ahydul** [comment]
#66 fixes this on 1.21.1

I can't be bothered to do other versions. If you study the changes you may be able to fix it for this version. The changes are really small.

**Comment by MINLEGO** [comment]
same for me
