### ISSUE TITLE
Skin doesn't change in-game

### ISSUE THREAD

**Issue by StoicIndividual** [cobrasrock/Skin-Swapper#8]
I'm not sure if this is intended but the only way I can get it to reliably change skins is if I restart the client

**Comment by cobrasrock** [comment]
I have recently been looking into the code and trying to find a fix but I will likely just open a minecraft bug report because it is an issue with the game and not my mod. The same behavior happens with changing from minecraft.net

**Comment by Lucipo** [comment]
bump for potential fix found

**Comment by cobrasrock** [comment]
Thank you for investigating this. I will try to get it fixed in the next version.
