### ISSUE TITLE
The "download from other player" button should be configurable

### ISSUE THREAD

**Issue by FewerFlaws** [cobrasrock/Skin-Swapper#9]
There should be a config option to disable the "download from other player" button.  Making it trivially easy to duplicate someone's skin is a headache for high-profile players such as server owners and streamers.

I'd much rather distribute this mod in a modpack with a collection of thematically-appropriate skins readily available and the "download from player" button disabled by default.

**Comment by cobrasrock** [comment]
In a future version I will likely add a config in modmenu. Thanks for the suggestion.
